version: "3"

services:
  go-custom:
    build:
      context: .
      dockerfile: Dockerfile.golang
    image: go-custom
    volumes:
      - .:/code:cached
    working_dir: /code
    env_file: .env
    environment:
      - GOPATH=/code/.go

  serverless:
    image: amaysim/serverless:3.36.0
    volumes:
      - .:/app:cached
    working_dir: /app
    env_file: .env

  mockery:
    image: vektra/mockery:v2
    volumes:
      - .:/code:cached
    working_dir: /code
